SET SERVEROUTPUT ON;

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE LOANS';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -942 THEN RAISE; END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE CUSTOMERS';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -942 THEN RAISE; END IF;
END;
/

CREATE TABLE CUSTOMERS (
    CUSTOMER_ID   NUMBER PRIMARY KEY,
    NAME          VARCHAR2(100)
);

CREATE TABLE LOANS (
    LOAN_ID        NUMBER PRIMARY KEY,
    CUSTOMER_ID    NUMBER,
    DUE_DATE       DATE,
    AMOUNT         NUMBER(12,2),
    CONSTRAINT fk_customer FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMERS(CUSTOMER_ID)
);

BEGIN
    INSERT INTO CUSTOMERS VALUES (1, 'John Smith');
    INSERT INTO CUSTOMERS VALUES (2, 'Alice Johnson');
    INSERT INTO CUSTOMERS VALUES (3, 'Robert Lee');
    INSERT INTO CUSTOMERS VALUES (4, 'Emily Clark');
    COMMIT;
END;
/

BEGIN
    INSERT INTO LOANS VALUES (101, 1, SYSDATE + 5, 5000.00);   -- due soon
    INSERT INTO LOANS VALUES (102, 2, SYSDATE + 15, 10000.00); -- due soon
    INSERT INTO LOANS VALUES (103, 3, SYSDATE + 40, 15000.00); -- not due
    INSERT INTO LOANS VALUES (104, 4, SYSDATE + 29, 7500.00);  -- due soon
    COMMIT;
END;
/

BEGIN
    FOR loan_rec IN (
        SELECT L.LOAN_ID, L.CUSTOMER_ID, L.DUE_DATE, L.AMOUNT, C.NAME
        FROM LOANS L
        JOIN CUSTOMERS C ON L.CUSTOMER_ID = C.CUSTOMER_ID
        WHERE L.DUE_DATE BETWEEN SYSDATE AND SYSDATE + 30
    )
    LOOP
        DBMS_OUTPUT.PUT_LINE(
            'Reminder: Loan ID ' || loan_rec.LOAN_ID ||
            ', Amount: $' || loan_rec.AMOUNT ||
            ', Due Date: ' || TO_CHAR(loan_rec.DUE_DATE, 'DD-Mon-YYYY') ||
            ', Customer: ' || loan_rec.NAME
        );
    END LOOP;
END;
/
